### ISSUE TITLE
Command: hub state ls prints `unset` instead of name of the stack

### ISSUE THREAD

**Issue by akranga** [agilestacks/hub-utils#2]
Steps to reproduce

1. Deploy stack that doesn't have `dns.domain` (see [example](https://github.com/agilestacks/kubeflow-stacks/tree/main/examples/gke-cluster)
2. Run command `hub state ls` 
3. See `unset` instead of ID of a stack...

Doesn't work: 
- [x] `hub state ls`
- [x] `hub state show`
- [x] `hub stack init `

**Comment by oginskis** [comment]
And what is expected behaviour?

**Comment by TheRealSpaceShip** [comment]
The fix is done. The current implementation of finding stack ID is next by priority:
1. Looking for `dns.domain` parameter
2. Looking for `dns.name` parameter
3. Looking in state location and take name leads before `hub`. Based on the current version for all 3 version of state location for each cloud provider (az://$HUB_STATE_BUCKET/$HUB_STATE_CONTAINER/$HUB_DOMAIN_NAME/hub/$STACK/hub.state, s3://$HUB_STATE_BUCKET/$HUB_DOMAIN_NAME/hub/$STACK/hub.state, gs://$HUB_STATE_BUCKET/$HUB_DOMAIN_NAME/hub/hub.state)
4. Use raw state location
