### ISSUE TITLE
Hub state produces inconsistent initiator

### ISSUE THREAD

**Issue by akranga** [agilestacks/hub-utils#3]
Running `hub state ls` for two different GKE stacks (one fork of another) getting inconsistent results

```
ID                                             NAME                                                STATUS      UPDATED      INITIATOR
melted-irving-981.epam.devops.delivery         GKE Sandbox Stack                                   undeployed  2 hours ago  john_doe
thick-brooksie-884.epam.devops.delivery        Kubeflow                                            deployed    2 hours ago  john_doe@mycompany.com
```

Where `melted-irking` has been created from Cloud Shell environment. 

Expected result: both stacks should show provide consistent output as: `john_doe@mycompany.com`

**Comment by TheRealSpaceShip** [comment]
The root cause of this issue is next. Hub CLI use `os.Get("USER")` to get the initiator of the last operation. That's where this inconsistency came from. I have worked around it by using `hub.userAccount` parameter as initiator and fallback to Hub CLI initiator value in case there is no such parameter.
